### ISSUE TITLE
is your demo really work?

### ISSUE THREAD

**Issue by sbh96** [sail-tunnel/sail#17]
hi i am really need a demo ios app for v2ray I find your repo but I think it isn't implemented v2ray cli binary , two question :
1-if is not completed are you implement v2ray inside this soon as possible?
2-how i can help you to develop this application i compiled cli binary v2ray core for ios if you want i can send it to you

if you are help me i can help you in v2board becouse I am laravel developer
we need this app in Iran because over government is block all of other vpns ,
we really need to v2ray support to access to free internet
@losgif  @ElforL  @jerry-bool

**Comment by jerry-bool** [comment]
I prefer to use clash or other proxy framework such as leaf rather than single protocol like v2ray.
I think it's a demo, not a full application. I will work on it, but still a lot of jobs to be done.

**Comment by sbh96** [comment]
> I prefer to use clash or other proxy framework such as leaf rather than single protocol like v2ray. I think it's a demo, not a full application. I will work on it, but still a lot of jobs to be done.

Leaf is good but isnt support vmess with alterid so cant use it as stable library

**Comment by losgif** [comment]
v2ray has some memory issues in iOS, unfortunately this requires modification of v2ray to make it work. We can consider designing a multi-core architecture to allow users to switch independently, welcome pr
