### ISSUE TITLE
2个flutter run报错

### ISSUE THREAD

**Issue by dsx5ds** [sail-tunnel/sail#18]
1.appid问题 package名称不能用-连接,改成_即可或者降低flutter版本为3.0.1
2.flutter run 安卓设备时报错
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
·············省略
lib/models/server_model.dart:68:33: Warning: Operand of null-aware operation '?.' has type 'ServerEntity' which excludes null.
 - 'ServerEntity' is from 'package:sail_app/entity/server_entity.dart' ('lib/entity/server_entity.dart').
              _serverEntityList![index]?.ping = duration;
·············省略
FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter_windows\flutter_3.0.1\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter_windows\flutter_3.0.1\bin\flutter.bat'' finished with non-zero exit value 1

环境
Flutter 3.0.1
Dart 2.17.1

**Comment by losgif** [comment]
fixed
