### ISSUE TITLE
Not listing Servers List

### ISSUE THREAD

**Issue by muzaffer72** [sail-tunnel/sail#20]
Even though I did all the settings. Server listings are not listed. The ping list is empty. Server selection stays on the White page. can you help with this problem

Logcat
E/flutter (31688): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
E/flutter (31688): #0      new UserSubscribeEntity.fromMap (package:sail/entity/user_subscribe_entity.dart:40:20)
E/flutter (31688): #1      UserService.userSubscribe.<anonymous closure> (package:sail/service/user_service.dart:28:34)
E/flutter (31688): <asynchronous suspension>
E/flutter (31688): #2      UserSubscribeModel.getUserSubscribe (package:sail/models/user_subscribe_model.dart:21:30)
E/flutter (31688): <asynchronous suspension>
E/flutter (31688): #3      HomePageState.didChangeDependencies (package:sail/pages/home/home_page.dart:69:7)
E/flutter (31688): <asynchronous suspension>
E/flutter (31688):

**Comment by bayuexg** [comment]
Hi, did you solve it? I met the same problem, it would be great if you could share it

**Comment by muzaffer72** [comment]
No, I haven't figured it out yet.

**Comment by muzaffer72** [comment]
> Hi, did you solve it? I met the same problem, it would be great if you could share it

You can fixed

**Comment by mumujie10** [comment]
Hello, I'm a new comer to Flutter. Have you solved this problem? I also encounter the same problem. Can I share the problem if I solve it?

**Comment by MHP370** [comment]
any body can fix it ??

**Comment by Mdrzxsony** [comment]
@jerry-bool Hello, can you send me a message on Telegram, I would like to do a project, the cost will be paid.
my telegram id @mmdrexa_hiis
