### ISSUE TITLE
安卓开启VPN正常，无法关闭VPN(Android can open VPN normally, unable to close VPN)

### ISSUE THREAD

**Issue by mumujie10** [sail-tunnel/sail#27]
在安卓设备中可进行vpn链接，但是无法进行关闭服务

**Comment by muzaffer72** [comment]
You can shared latest your source code. Not listing server for me.

**Comment by muzaffer72** [comment]
you can fixed

**Comment by C007G** [comment]
> 在安卓设备中可进行vpn链接，但是无法进行关闭服务

无法关闭服务解决了吗，我的也无法断开
