### ISSUE TITLE
登录问题 已经解决，节点不显示

### ISSUE THREAD

**Issue by onjacky** [sail-tunnel/sail#31]
如题

**Comment by losgif** [comment]
大概率是数据类型不匹配，检查一下控制台

**Comment by ffkaan** [comment]
您好，我通过 V2board 支持 v2ray 协议。 我可以登录，但看不到服务器。 你能再解释一下我到底需要做什么吗？
flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'bool' is not a subtype of type 'int'

**Comment by onjacky** [comment]
您好：
     您的来信我定将详细阅读。但由于本人时间与精力有限，回信的先后次序为“客户、亲人、同事、朋友、陌生人”。如果为您带来不便还请谅解。
