### ISSUE TITLE
安卓打开VPN后无法关闭

### ISSUE THREAD

**Issue by onjacky** [sail-tunnel/sail#32]
安卓打开VPN后无法关闭

**Comment by losgif** [comment]
建议提供一下控制台输出信息以便定位问题

**Comment by onjacky** [comment]
![image](https://user-images.githubusercontent.com/93144036/233680138-425845db-a525-449c-832d-6219cf6a6c4e.png)
说是找不到x86_64里的libleaf.so文件，这是在run状态下出现的。这种状态下，点击连接VPN，就会闪退。
提示找不到x86_64文件。
在[Leaf](https://github.com/eycorsican/leaf)下载最新的libleaf.so，建立相应文件夹拷贝进去后，不会报错，但是依然闪退。断开连接模拟器连接。 没有真机调试。
生成release  apk 后，不用最新版的libleaf.so，模拟器、真机测试为，有的情况下闪退。有的情况下可以连接vpn，但是无法关闭。有的时候连接VPN 一段时间自动闪退。 如果替换新版的Leaf，直接闪退。
修改了MainActivity 里面的一些代码，release  的闪退情况少了，但是连接后依然无法关闭、断开连接。
测试环境：雷电模拟器、华为手机、小米手机。
将startService更换为startForegroundService 测试结果一样。

**Comment by losgif** [comment]
以下教程应该会有所帮助

https://docs.rs/jni/latest/jni/
https://developer.android.com/training/articles/perf-jni?hl=zh-cn

**Comment by losgif** [comment]
> 说是找不到x86_64里的libleaf.so文件，这是在run状态下出现的。这种状态下，点击连接VPN，就会闪退。
> 提示找不到x86_64文件。

android 模拟器CPU一般使用x86_64指令集，真机使用arm64，打包好的一般是单架构的，无法兼顾，测试用要自行合并。

> 在[Leaf](https://github.com/eycorsican/leaf)下载最新的libleaf.so，建立相应文件夹拷贝进去后，不会报错，但是依然闪退。断开连接模拟器连接。 没有真机调试。

leaf 仓库并没有直接提供android可用二进制库，强行执行不同架构二进制文件必然如此

> 生成release apk 后，不用最新版的libleaf.so，模拟器、真机测试为，有的情况下闪退。有的情况下可以连接vpn，但是无法关闭。有的时候连接VPN 一段时间自动闪退。 如果替换新版的Leaf，直接闪退。

和上边差不多理由差不多，而且JNI对于导出的函数名有命名要求，参考上方教程链接

> 修改了MainActivity 里面的一些代码，release 的闪退情况少了，但是连接后依然无法关闭、断开连接。
> 测试环境：雷电模拟器、华为手机、小米手机。
> 将startService更换为startForegroundService 测试结果一样。

完成上方的操作基本可以消除此类问题

**Comment by fantasydove** [comment]
> ![image](https://user-images.githubusercontent.com/93144036/233680138-425845db-a525-449c-832d-6219cf6a6c4e.png) 说是找不到x86_64里的libleaf.so文件，这是在run状态下出现的。这种状态下，点击连接VPN，就会闪退。 提示找不到x86_64文件。 在[Leaf](https://github.com/eycorsican/leaf)下载最新的libleaf.so，建立相应文件夹拷贝进去后，不会报错，但是依然闪退。断开连接模拟器连接。 没有真机调试。 生成release apk 后，不用最新版的libleaf.so，模拟器、真机测试为，有的情况下闪退。有的情况下可以连接vpn，但是无法关闭。有的时候连接VPN 一段时间自动闪退。 如果替换新版的Leaf，直接闪退。 修改了MainActivity 里面的一些代码，release 的闪退情况少了，但是连接后依然无法关闭、断开连接。 测试环境：雷电模拟器、华为手机、小米手机。 将startService更换为startForegroundService 测试结果一样。

解决了么，怎么解决的，求教下
