### ISSUE TITLE
Not show the list of nodes (Android)

### ISSUE THREAD

**Issue by demianrey** [sail-tunnel/sail#6]
I have been able to compile the application on Android but the list of user nodes does not show anything, is it normal? I am using v2board

**Comment by zhang757396194** [comment]
不是完整代码

------------------ Original ------------------
From: demianrey ***@***.***&gt;
Date: Wed,Jun 22,2022 0:49 AM
To: losgif/sail ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [losgif/sail] Not show the list of nodes (Android) (Issue #6)





 
I have been able to compile the application on Android but the list of user nodes does not show anything, is it normal?

**Comment by losgif** [comment]
> The iOS version is complete?

support iOS first.

**Comment by demianrey** [comment]
> > The iOS version is complete?
> 
> support iOS first.

Ok, thanks for your effort

**Comment by ogbeh** [comment]
> > The iOS version is complete?
> 
> support iOS first.
What if we could provide an android device for you? we could setup a paypal or something?

**Comment by losgif** [comment]
> > > The iOS version is complete?
> > 
> > 
> > support iOS first.
> > What if we could provide an android device for you? we could setup a paypal or something?

The UI framework was still in development and the necessity for Android devices came later.

**Comment by demianrey** [comment]
> The UI framework was still in development and the necessity for Android devices came later.

thanks for the improvement, but the error according to the log is as follows:
 [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'String' is not a subtype of type 'int'

**Comment by sdjnpoi** [comment]
首页选择节点后，节点列表可以自动缩回去

**Comment by muzaffer72** [comment]
> > The UI framework was still in development and the necessity for Android devices came later.
> 
> thanks for the improvement, but the error according to the log is as follows: [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'String' is not a subtype of type 'int'
> 
> I think that is the reason why the connections do not appear in android

I have same problem. You can fixed ?

**Comment by muzaffer72** [comment]
> Uygulamayı Android'de derleyebildim ancak kullanıcı düğümleri listesi hiçbir şey göstermiyor, normal mi? v2board kullanıyorum

Disable v2ray  node on v2board .. This have a problem

**Comment by zhang757396194** [comment]
不公开

------------------ Original ------------------
From: demianrey ***@***.***&gt;
Date: Wed,Jun 22,2022 0:52 AM
To: losgif/sail ***@***.***&gt;
Cc: zhang757396194 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [losgif/sail] Not show the list of nodes (Android) (Issue #6)





 
The iOS version is complete?

**Comment by losgif** [comment]
android is build available now
